---
- name: Copy static configuration files
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '0664'
  loop:
    - { src: 'default.yml', dest: '{{ traefik_folder }}/data/config.d/default.yml' }

- name: Render template files
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '0664'
  loop:
    - { src: '.env.j2', dest: '{{ traefik_folder }}/.env' }
    - { src: 'traefik.yml.j2', dest: '{{ traefik_folder }}/data/traefik.yml' }
    - { src: 'docker-compose.yml.j2', dest: '{{ traefik_folder }}/docker-compose.yml' }
