---
- name: Stop existing Traefik container (if any)
  community.docker.docker_compose:
    project_src: '{{ traefik_folder }}'
    state: absent
  ignore_errors: true

- name: Build Traefik Docker image
  community.docker.docker_image:
    build:
      path: '{{ traefik_folder }}'
    name: traefik_skullit
    tag: latest
  when: traefik_active | default(false)

- name: Start Traefik container
  community.docker.docker_compose:
    project_src: '{{ traefik_folder }}'
    state: present
    recreate: always
  when: traefik_active | default(false)
