---

- name: Setup prerequisites
  import_tasks: setup.yml

- name: Configure Cloudflare DNS (if applicable)
  import_tasks: cloudflare.yml
  when: traefik_certresolver == "cloudflare"

- name: Deploy configuration files
  import_tasks: config.yml

- name: Handle wildcard certificates (if applicable)
  import_tasks: wildcard.yml
  when: traefik_certresolver == "wildcard"

- name: Handle Traefik container
  import_tasks: handler.yml