---
- name: Create Traefik config.d directory
  file:
    path: "{{ traefik_folder }}/data/config.d"
    state: directory
    mode: '0775'
    recurse: yes

- name: Create acme.json if it doesn't exist
  file:
    path: '{{ traefik_folder }}/data/acme.json'
    state: touch
    mode: '0600'

- name: Ensure acme.json has correct permissions
  file:
    path: '{{ traefik_folder }}/data/acme.json'
    mode: '0600'

- name: Create traefik.log if it doesn't exist
  file:
    path: '{{ traefik_folder }}/data/traefik.log'
    state: touch
    mode: '0755'
